services:
  db:
    image: postgres
    container_name: exorcist-db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    ports:
      - ${DATABASE_PORT}:5432
  plantUml:
    container_name: plant-uml
    image: plantuml/plantuml-server:jetty
    ports:
      - 8080:8080
