services:
  db:
    image: postgres
    container_name: exorcist-db-dev
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    ports:
      - ${DATABASE_PORT}:5432
