//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var MediaTypeEnum = &struct {
	Primary postgres.StringExpression
	Asset   postgres.StringExpression
}{
	Primary: postgres.NewEnumValue("primary"),
	Asset:   postgres.NewEnumValue("asset"),
}
