//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var MediaPerson = newMediaPersonTable("public", "media_person", "")

type mediaPersonTable struct {
	postgres.Table

	// Columns
	ID       postgres.ColumnString
	Created  postgres.ColumnTimestamp
	Modified postgres.ColumnTimestamp
	MediaID  postgres.ColumnString
	PersonID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type MediaPersonTable struct {
	mediaPersonTable

	EXCLUDED mediaPersonTable
}

// AS creates new MediaPersonTable with assigned alias
func (a MediaPersonTable) AS(alias string) *MediaPersonTable {
	return newMediaPersonTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MediaPersonTable with assigned schema name
func (a MediaPersonTable) FromSchema(schemaName string) *MediaPersonTable {
	return newMediaPersonTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MediaPersonTable with assigned table prefix
func (a MediaPersonTable) WithPrefix(prefix string) *MediaPersonTable {
	return newMediaPersonTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MediaPersonTable with assigned table suffix
func (a MediaPersonTable) WithSuffix(suffix string) *MediaPersonTable {
	return newMediaPersonTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMediaPersonTable(schemaName, tableName, alias string) *MediaPersonTable {
	return &MediaPersonTable{
		mediaPersonTable: newMediaPersonTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newMediaPersonTableImpl("", "excluded", ""),
	}
}

func newMediaPersonTableImpl(schemaName, tableName, alias string) mediaPersonTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		CreatedColumn  = postgres.TimestampColumn("created")
		ModifiedColumn = postgres.TimestampColumn("modified")
		MediaIDColumn  = postgres.StringColumn("media_id")
		PersonIDColumn = postgres.StringColumn("person_id")
		allColumns     = postgres.ColumnList{IDColumn, CreatedColumn, ModifiedColumn, MediaIDColumn, PersonIDColumn}
		mutableColumns = postgres.ColumnList{CreatedColumn, ModifiedColumn, MediaIDColumn, PersonIDColumn}
	)

	return mediaPersonTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		Created:  CreatedColumn,
		Modified: ModifiedColumn,
		MediaID:  MediaIDColumn,
		PersonID: PersonIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
