//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var MediaProgress = newMediaProgressTable("public", "media_progress", "")

type mediaProgressTable struct {
	postgres.Table

	// Columns
	ID       postgres.ColumnString
	UserID   postgres.ColumnString
	MediaID  postgres.ColumnString
	Created  postgres.ColumnTimestamp
	Modified postgres.ColumnTimestamp
	GhostID  postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type MediaProgressTable struct {
	mediaProgressTable

	EXCLUDED mediaProgressTable
}

// AS creates new MediaProgressTable with assigned alias
func (a MediaProgressTable) AS(alias string) *MediaProgressTable {
	return newMediaProgressTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MediaProgressTable with assigned schema name
func (a MediaProgressTable) FromSchema(schemaName string) *MediaProgressTable {
	return newMediaProgressTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MediaProgressTable with assigned table prefix
func (a MediaProgressTable) WithPrefix(prefix string) *MediaProgressTable {
	return newMediaProgressTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MediaProgressTable with assigned table suffix
func (a MediaProgressTable) WithSuffix(suffix string) *MediaProgressTable {
	return newMediaProgressTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMediaProgressTable(schemaName, tableName, alias string) *MediaProgressTable {
	return &MediaProgressTable{
		mediaProgressTable: newMediaProgressTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newMediaProgressTableImpl("", "excluded", ""),
	}
}

func newMediaProgressTableImpl(schemaName, tableName, alias string) mediaProgressTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		UserIDColumn   = postgres.StringColumn("user_id")
		MediaIDColumn  = postgres.StringColumn("media_id")
		CreatedColumn  = postgres.TimestampColumn("created")
		ModifiedColumn = postgres.TimestampColumn("modified")
		GhostIDColumn  = postgres.IntegerColumn("ghost_id")
		allColumns     = postgres.ColumnList{IDColumn, UserIDColumn, MediaIDColumn, CreatedColumn, ModifiedColumn, GhostIDColumn}
		mutableColumns = postgres.ColumnList{UserIDColumn, MediaIDColumn, CreatedColumn, ModifiedColumn, GhostIDColumn}
	)

	return mediaProgressTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		UserID:   UserIDColumn,
		MediaID:  MediaIDColumn,
		Created:  CreatedColumn,
		Modified: ModifiedColumn,
		GhostID:  GhostIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
