//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PersonAlias = newPersonAliasTable("public", "person_alias", "")

type personAliasTable struct {
	postgres.Table

	// Columns
	ID       postgres.ColumnString
	Alias_   postgres.ColumnString
	Created  postgres.ColumnTimestamp
	Modified postgres.ColumnTimestamp
	PersonID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PersonAliasTable struct {
	personAliasTable

	EXCLUDED personAliasTable
}

// AS creates new PersonAliasTable with assigned alias
func (a PersonAliasTable) AS(alias string) *PersonAliasTable {
	return newPersonAliasTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PersonAliasTable with assigned schema name
func (a PersonAliasTable) FromSchema(schemaName string) *PersonAliasTable {
	return newPersonAliasTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PersonAliasTable with assigned table prefix
func (a PersonAliasTable) WithPrefix(prefix string) *PersonAliasTable {
	return newPersonAliasTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PersonAliasTable with assigned table suffix
func (a PersonAliasTable) WithSuffix(suffix string) *PersonAliasTable {
	return newPersonAliasTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPersonAliasTable(schemaName, tableName, alias string) *PersonAliasTable {
	return &PersonAliasTable{
		personAliasTable: newPersonAliasTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newPersonAliasTableImpl("", "excluded", ""),
	}
}

func newPersonAliasTableImpl(schemaName, tableName, alias string) personAliasTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		Alias_Column   = postgres.StringColumn("alias")
		CreatedColumn  = postgres.TimestampColumn("created")
		ModifiedColumn = postgres.TimestampColumn("modified")
		PersonIDColumn = postgres.StringColumn("person_id")
		allColumns     = postgres.ColumnList{IDColumn, Alias_Column, CreatedColumn, ModifiedColumn, PersonIDColumn}
		mutableColumns = postgres.ColumnList{Alias_Column, CreatedColumn, ModifiedColumn, PersonIDColumn}
		defaultColumns = postgres.ColumnList{IDColumn, CreatedColumn, ModifiedColumn}
	)

	return personAliasTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		Alias_:   Alias_Column,
		Created:  CreatedColumn,
		Modified: ModifiedColumn,
		PersonID: PersonIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
