GET http://localhost:8181
###
GET http://localhost:8181/api/libraries/scan

### Login
POST http://localhost:8181/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Logout

GET http://localhost:8181/logout

### Users

GET http://localhost:8181/api/users

### Create User

POST http://localhost:8181/api/users
Content-Type: application/json

{
  "username": "another",
  "password": "admin"
}

### Create library

POST http://localhost:8181/api/libraries
Content-Type: application

{
  "name": "new name"
}
