// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/image/image.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/image/image.go
//

// Package mock_imageService is a generated GoMock package.
package mock_imageService

import (
	gomock "go.uber.org/mock/gomock"
)

// MockIImageService is a mock of IImageService interface.
type MockIImageService struct {
	ctrl     *gomock.Controller
	recorder *MockIImageServiceMockRecorder
	isgomock struct{}
}

// MockIImageServiceMockRecorder is the mock recorder for MockIImageService.
type MockIImageServiceMockRecorder struct {
	mock *MockIImageService
}

// NewMockIImageService creates a new mock instance.
func NewMockIImageService(ctrl *gomock.Controller) *MockIImageService {
	mock := &MockIImageService{ctrl: ctrl}
	mock.recorder = &MockIImageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIImageService) EXPECT() *MockIImageServiceMockRecorder {
	return m.recorder
}
