//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Job struct {
	ID        uuid.UUID `sql:"primary_key"`
	JobParent *uuid.UUID
	Priority  int16
	JobType   JobTypeEnum
	Status    JobStatusEnum
	Data      *string
	Outcome   *string
	Created   time.Time
	Modified  time.Time
}
