//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Media struct {
	ID            uuid.UUID `sql:"primary_key"`
	LibraryPathID uuid.UUID
	Path          string
	FileName      string
	Title         string
	MediaType     MediaTypeEnum
	Size          int64
	Checksum      *string
	Added         time.Time
	Deleted       bool
	Exists        bool
	Created       time.Time
	Modified      time.Time
}
