//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Video struct {
	ID            uuid.UUID `sql:"primary_key"`
	LibraryPathID uuid.UUID
	RelativePath  string
	Title         string
	FileName      string
	Height        int32
	Width         int32
	Runtime       float64
	Size          int64
	Checksum      *string
	Added         time.Time
	Deleted       bool
	Exists        bool
	Created       time.Time
	Modified      time.Time
}
