//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type VideoMedia struct {
	ID             uuid.UUID `sql:"primary_key"`
	VideoID        uuid.UUID
	MediaID        uuid.UUID
	VideoMediaType VideoMediaTypeEnum
	Created        time.Time
	Modified       time.Time
}
