//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ConvertJobs struct {
	ID                 int32 `sql:"primary_key"`
	Title              string
	Path               string
	VideoId            int32
	JobId              int32
	ConstantRateFactor *int32
	VariableBitrate    *int32
	ForcePixelFormat   *string
	Height             int32
	Width              int32
}
