//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type GenerateThumbnailsJobs struct {
	ID        int32 `sql:"primary_key"`
	Overwrite int32
	LibraryId int32
	JobId     int32
}
