//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PlaylistVideos struct {
	ID         int32 `sql:"primary_key"`
	CreatedAt  string
	VideoId    int32
	PlaylistId int32
}
