//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Videos struct {
	ID                 int32 `sql:"primary_key"`
	FileName           string
	Title              string
	Path               string
	LibraryPathId      int32
	DateAdded          string
	Created            string
	Height             int32
	LastMetadataUpdate string
	LastNfoScan        string
	Runtime            float32
	Size               int32
	Width              int32
}
