// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/media/media.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/media/media.go
//

// Package mock_mediaService is a generated GoMock package.
package mock_mediaService

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/slugger7/exorcist/internal/db/exorcist/public/model"
	models "github.com/slugger7/exorcist/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMediaService is a mock of MediaService interface.
type MockMediaService struct {
	ctrl     *gomock.Controller
	recorder *MockMediaServiceMockRecorder
	isgomock struct{}
}

// MockMediaServiceMockRecorder is the mock recorder for MockMediaService.
type MockMediaServiceMockRecorder struct {
	mock *MockMediaService
}

// NewMockMediaService creates a new mock instance.
func NewMockMediaService(ctrl *gomock.Controller) *MockMediaService {
	mock := &MockMediaService{ctrl: ctrl}
	mock.recorder = &MockMediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaService) EXPECT() *MockMediaServiceMockRecorder {
	return m.recorder
}

// AddPerson mocks base method.
func (m *MockMediaService) AddPerson(id, personId uuid.UUID) (*model.MediaPerson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPerson", id, personId)
	ret0, _ := ret[0].(*model.MediaPerson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPerson indicates an expected call of AddPerson.
func (mr *MockMediaServiceMockRecorder) AddPerson(id, personId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPerson", reflect.TypeOf((*MockMediaService)(nil).AddPerson), id, personId)
}

// AddTag mocks base method.
func (m *MockMediaService) AddTag(id, tagId uuid.UUID) (*model.MediaTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", id, tagId)
	ret0, _ := ret[0].(*model.MediaTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTag indicates an expected call of AddTag.
func (mr *MockMediaServiceMockRecorder) AddTag(id, tagId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockMediaService)(nil).AddTag), id, tagId)
}

// SetPeople mocks base method.
func (m *MockMediaService) SetPeople(id uuid.UUID, people []string) (*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPeople", id, people)
	ret0, _ := ret[0].(*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPeople indicates an expected call of SetPeople.
func (mr *MockMediaServiceMockRecorder) SetPeople(id, people any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPeople", reflect.TypeOf((*MockMediaService)(nil).SetPeople), id, people)
}

// SetTags mocks base method.
func (m *MockMediaService) SetTags(id uuid.UUID, tags []string) (*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTags", id, tags)
	ret0, _ := ret[0].(*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTags indicates an expected call of SetTags.
func (mr *MockMediaServiceMockRecorder) SetTags(id, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTags", reflect.TypeOf((*MockMediaService)(nil).SetTags), id, tags)
}
