// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/media/media.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/media/media.go
//

// Package mock_mediaService is a generated GoMock package.
package mock_mediaService

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/slugger7/exorcist/internal/db/exorcist/public/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMediaService is a mock of MediaService interface.
type MockMediaService struct {
	ctrl     *gomock.Controller
	recorder *MockMediaServiceMockRecorder
	isgomock struct{}
}

// MockMediaServiceMockRecorder is the mock recorder for MockMediaService.
type MockMediaServiceMockRecorder struct {
	mock *MockMediaService
}

// NewMockMediaService creates a new mock instance.
func NewMockMediaService(ctrl *gomock.Controller) *MockMediaService {
	mock := &MockMediaService{ctrl: ctrl}
	mock.recorder = &MockMediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaService) EXPECT() *MockMediaServiceMockRecorder {
	return m.recorder
}

// AddPerson mocks base method.
func (m *MockMediaService) AddPerson(id, personId uuid.UUID) (*model.MediaPerson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPerson", id, personId)
	ret0, _ := ret[0].(*model.MediaPerson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPerson indicates an expected call of AddPerson.
func (mr *MockMediaServiceMockRecorder) AddPerson(id, personId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPerson", reflect.TypeOf((*MockMediaService)(nil).AddPerson), id, personId)
}

// AddTag mocks base method.
func (m *MockMediaService) AddTag(id, tagId uuid.UUID) (*model.MediaTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", id, tagId)
	ret0, _ := ret[0].(*model.MediaTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTag indicates an expected call of AddTag.
func (mr *MockMediaServiceMockRecorder) AddTag(id, tagId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockMediaService)(nil).AddTag), id, tagId)
}

// Delete mocks base method.
func (m *MockMediaService) Delete(id uuid.UUID, physical bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, physical)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaServiceMockRecorder) Delete(id, physical any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMediaService)(nil).Delete), id, physical)
}

// LogProgress mocks base method.
func (m *MockMediaService) LogProgress(id, userId uuid.UUID, progress float64) (*model.MediaProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogProgress", id, userId, progress)
	ret0, _ := ret[0].(*model.MediaProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogProgress indicates an expected call of LogProgress.
func (mr *MockMediaServiceMockRecorder) LogProgress(id, userId, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogProgress", reflect.TypeOf((*MockMediaService)(nil).LogProgress), id, userId, progress)
}
