//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var FavouriteActors = newFavouriteActorsTable("", "FavouriteActors", "")

type favouriteActorsTable struct {
	sqlite.Table

	// Columns
	ID      sqlite.ColumnInteger
	ActorId sqlite.ColumnInteger
	UserId  sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type FavouriteActorsTable struct {
	favouriteActorsTable

	EXCLUDED favouriteActorsTable
}

// AS creates new FavouriteActorsTable with assigned alias
func (a FavouriteActorsTable) AS(alias string) *FavouriteActorsTable {
	return newFavouriteActorsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FavouriteActorsTable with assigned schema name
func (a FavouriteActorsTable) FromSchema(schemaName string) *FavouriteActorsTable {
	return newFavouriteActorsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FavouriteActorsTable with assigned table prefix
func (a FavouriteActorsTable) WithPrefix(prefix string) *FavouriteActorsTable {
	return newFavouriteActorsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FavouriteActorsTable with assigned table suffix
func (a FavouriteActorsTable) WithSuffix(suffix string) *FavouriteActorsTable {
	return newFavouriteActorsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFavouriteActorsTable(schemaName, tableName, alias string) *FavouriteActorsTable {
	return &FavouriteActorsTable{
		favouriteActorsTable: newFavouriteActorsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newFavouriteActorsTableImpl("", "excluded", ""),
	}
}

func newFavouriteActorsTableImpl(schemaName, tableName, alias string) favouriteActorsTable {
	var (
		IDColumn       = sqlite.IntegerColumn("Id")
		ActorIdColumn  = sqlite.IntegerColumn("ActorId")
		UserIdColumn   = sqlite.IntegerColumn("UserId")
		allColumns     = sqlite.ColumnList{IDColumn, ActorIdColumn, UserIdColumn}
		mutableColumns = sqlite.ColumnList{ActorIdColumn, UserIdColumn}
	)

	return favouriteActorsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:      IDColumn,
		ActorId: ActorIdColumn,
		UserId:  UserIdColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
