//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Libraries = newLibrariesTable("", "Libraries", "")

type librariesTable struct {
	sqlite.Table

	// Columns
	ID   sqlite.ColumnInteger
	Name sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type LibrariesTable struct {
	librariesTable

	EXCLUDED librariesTable
}

// AS creates new LibrariesTable with assigned alias
func (a LibrariesTable) AS(alias string) *LibrariesTable {
	return newLibrariesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LibrariesTable with assigned schema name
func (a LibrariesTable) FromSchema(schemaName string) *LibrariesTable {
	return newLibrariesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LibrariesTable with assigned table prefix
func (a LibrariesTable) WithPrefix(prefix string) *LibrariesTable {
	return newLibrariesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LibrariesTable with assigned table suffix
func (a LibrariesTable) WithSuffix(suffix string) *LibrariesTable {
	return newLibrariesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLibrariesTable(schemaName, tableName, alias string) *LibrariesTable {
	return &LibrariesTable{
		librariesTable: newLibrariesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newLibrariesTableImpl("", "excluded", ""),
	}
}

func newLibrariesTableImpl(schemaName, tableName, alias string) librariesTable {
	var (
		IDColumn       = sqlite.IntegerColumn("Id")
		NameColumn     = sqlite.StringColumn("Name")
		allColumns     = sqlite.ColumnList{IDColumn, NameColumn}
		mutableColumns = sqlite.ColumnList{NameColumn}
	)

	return librariesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
