// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/video/video.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/video/video.go
//

// Package mock_videoRepository is a generated GoMock package.
package mock_videoRepository

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/slugger7/exorcist/internal/db/exorcist/public/model"
	videoRepository "github.com/slugger7/exorcist/internal/repository/video"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoRepository is a mock of VideoRepository interface.
type MockVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVideoRepositoryMockRecorder
	isgomock struct{}
}

// MockVideoRepositoryMockRecorder is the mock recorder for MockVideoRepository.
type MockVideoRepositoryMockRecorder struct {
	mock *MockVideoRepository
}

// NewMockVideoRepository creates a new mock instance.
func NewMockVideoRepository(ctrl *gomock.Controller) *MockVideoRepository {
	mock := &MockVideoRepository{ctrl: ctrl}
	mock.recorder = &MockVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoRepository) EXPECT() *MockVideoRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockVideoRepository) GetAll() ([]model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockVideoRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockVideoRepository)(nil).GetAll))
}

// GetByIdWithMedia mocks base method.
func (m *MockVideoRepository) GetByIdWithMedia(id uuid.UUID) (*videoRepository.MediaVideoModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdWithMedia", id)
	ret0, _ := ret[0].(*videoRepository.MediaVideoModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdWithMedia indicates an expected call of GetByIdWithMedia.
func (mr *MockVideoRepositoryMockRecorder) GetByIdWithMedia(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdWithMedia", reflect.TypeOf((*MockVideoRepository)(nil).GetByIdWithMedia), id)
}

// GetByMediaId mocks base method.
func (m *MockVideoRepository) GetByMediaId(id uuid.UUID) (*videoRepository.MediaVideoModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMediaId", id)
	ret0, _ := ret[0].(*videoRepository.MediaVideoModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMediaId indicates an expected call of GetByMediaId.
func (mr *MockVideoRepositoryMockRecorder) GetByMediaId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMediaId", reflect.TypeOf((*MockVideoRepository)(nil).GetByMediaId), id)
}

// Insert mocks base method.
func (m *MockVideoRepository) Insert(models []model.Video) ([]model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", models)
	ret0, _ := ret[0].([]model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockVideoRepositoryMockRecorder) Insert(models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockVideoRepository)(nil).Insert), models)
}
