// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/tag/tag.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/tag/tag.go
//

// Package mock_tagRepository is a generated GoMock package.
package mock_tagRepository

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/slugger7/exorcist/internal/db/exorcist/public/model"
	dto "github.com/slugger7/exorcist/internal/dto"
	models "github.com/slugger7/exorcist/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// AddToMedia mocks base method.
func (m *MockTagRepository) AddToMedia(mediaTags []model.MediaTag) ([]model.MediaTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToMedia", mediaTags)
	ret0, _ := ret[0].([]model.MediaTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToMedia indicates an expected call of AddToMedia.
func (mr *MockTagRepositoryMockRecorder) AddToMedia(mediaTags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToMedia", reflect.TypeOf((*MockTagRepository)(nil).AddToMedia), mediaTags)
}

// Create mocks base method.
func (m *MockTagRepository) Create(names []string) ([]model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", names)
	ret0, _ := ret[0].([]model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTagRepositoryMockRecorder) Create(names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagRepository)(nil).Create), names)
}

// GetAll mocks base method.
func (m *MockTagRepository) GetAll(search dto.TagSearchDTO) ([]model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", search)
	ret0, _ := ret[0].([]model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTagRepositoryMockRecorder) GetAll(search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTagRepository)(nil).GetAll), search)
}

// GetById mocks base method.
func (m *MockTagRepository) GetById(id uuid.UUID) (*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockTagRepositoryMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockTagRepository)(nil).GetById), id)
}

// GetByName mocks base method.
func (m *MockTagRepository) GetByName(name string) (*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTagRepositoryMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTagRepository)(nil).GetByName), name)
}

// GetMedia mocks base method.
func (m *MockTagRepository) GetMedia(id, userId uuid.UUID, search dto.MediaSearchDTO) (*dto.PageDTO[models.MediaOverviewModel], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedia", id, userId, search)
	ret0, _ := ret[0].(*dto.PageDTO[models.MediaOverviewModel])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedia indicates an expected call of GetMedia.
func (mr *MockTagRepositoryMockRecorder) GetMedia(id, userId, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedia", reflect.TypeOf((*MockTagRepository)(nil).GetMedia), id, userId, search)
}

// RemoveFromMedia mocks base method.
func (m *MockTagRepository) RemoveFromMedia(mediaTag model.MediaTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromMedia", mediaTag)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromMedia indicates an expected call of RemoveFromMedia.
func (mr *MockTagRepositoryMockRecorder) RemoveFromMedia(mediaTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromMedia", reflect.TypeOf((*MockTagRepository)(nil).RemoveFromMedia), mediaTag)
}

// Update mocks base method.
func (m_2 *MockTagRepository) Update(m model.Tag) (*model.Tag, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", m)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTagRepositoryMockRecorder) Update(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagRepository)(nil).Update), m)
}
