//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type LibraryPath struct {
	ID        uuid.UUID `sql:"primary_key"`
	LibraryID uuid.UUID
	Path      string
	Created   time.Time
	Modified  time.Time
	GhostID   *int32
}
