// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/image/image.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/image/image.go
//

// Package mock_imageRepository is a generated GoMock package.
package mock_imageRepository

import (
	reflect "reflect"

	model "github.com/slugger7/exorcist/internal/db/exorcist/public/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIImageRepository is a mock of IImageRepository interface.
type MockIImageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIImageRepositoryMockRecorder
	isgomock struct{}
}

// MockIImageRepositoryMockRecorder is the mock recorder for MockIImageRepository.
type MockIImageRepositoryMockRecorder struct {
	mock *MockIImageRepository
}

// NewMockIImageRepository creates a new mock instance.
func NewMockIImageRepository(ctrl *gomock.Controller) *MockIImageRepository {
	mock := &MockIImageRepository{ctrl: ctrl}
	mock.recorder = &MockIImageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIImageRepository) EXPECT() *MockIImageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIImageRepository) Create(model *model.Image) (*model.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", model)
	ret0, _ := ret[0].(*model.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIImageRepositoryMockRecorder) Create(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIImageRepository)(nil).Create), model)
}
