//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var LibraryTypeEnum = &struct {
	Image postgres.StringExpression
	Video postgres.StringExpression
	Mixed postgres.StringExpression
}{
	Image: postgres.NewEnumValue("image"),
	Video: postgres.NewEnumValue("video"),
	Mixed: postgres.NewEnumValue("mixed"),
}
