// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/video/video.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/video/video.go
//

// Package mock_videoRepository is a generated GoMock package.
package mock_videoRepository

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/slugger7/exorcist/internal/db/exorcist/public/model"
	videoRepository "github.com/slugger7/exorcist/internal/repository/video"
	gomock "go.uber.org/mock/gomock"
)

// MockIVideoRepository is a mock of IVideoRepository interface.
type MockIVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIVideoRepositoryMockRecorder
	isgomock struct{}
}

// MockIVideoRepositoryMockRecorder is the mock recorder for MockIVideoRepository.
type MockIVideoRepositoryMockRecorder struct {
	mock *MockIVideoRepository
}

// NewMockIVideoRepository creates a new mock instance.
func NewMockIVideoRepository(ctrl *gomock.Controller) *MockIVideoRepository {
	mock := &MockIVideoRepository{ctrl: ctrl}
	mock.recorder = &MockIVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIVideoRepository) EXPECT() *MockIVideoRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockIVideoRepository) GetAll() ([]model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIVideoRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIVideoRepository)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockIVideoRepository) GetById(id uuid.UUID) (*model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIVideoRepositoryMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIVideoRepository)(nil).GetById), id)
}

// GetByIdWithLibraryPath mocks base method.
func (m *MockIVideoRepository) GetByIdWithLibraryPath(id uuid.UUID) (*videoRepository.VideoLibraryPathModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdWithLibraryPath", id)
	ret0, _ := ret[0].(*videoRepository.VideoLibraryPathModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdWithLibraryPath indicates an expected call of GetByIdWithLibraryPath.
func (mr *MockIVideoRepositoryMockRecorder) GetByIdWithLibraryPath(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdWithLibraryPath", reflect.TypeOf((*MockIVideoRepository)(nil).GetByIdWithLibraryPath), id)
}

// GetByLibraryPathId mocks base method.
func (m *MockIVideoRepository) GetByLibraryPathId(id uuid.UUID) ([]model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLibraryPathId", id)
	ret0, _ := ret[0].([]model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLibraryPathId indicates an expected call of GetByLibraryPathId.
func (mr *MockIVideoRepositoryMockRecorder) GetByLibraryPathId(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLibraryPathId", reflect.TypeOf((*MockIVideoRepository)(nil).GetByLibraryPathId), id)
}

// GetOverview mocks base method.
func (m *MockIVideoRepository) GetOverview() ([]videoRepository.VideoOverviewModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverview")
	ret0, _ := ret[0].([]videoRepository.VideoOverviewModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverview indicates an expected call of GetOverview.
func (mr *MockIVideoRepositoryMockRecorder) GetOverview() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverview", reflect.TypeOf((*MockIVideoRepository)(nil).GetOverview))
}

// Insert mocks base method.
func (m *MockIVideoRepository) Insert(models []model.Video) ([]model.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", models)
	ret0, _ := ret[0].([]model.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockIVideoRepositoryMockRecorder) Insert(models any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIVideoRepository)(nil).Insert), models)
}

// UpdateChecksum mocks base method.
func (m *MockIVideoRepository) UpdateChecksum(video *model.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChecksum", video)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChecksum indicates an expected call of UpdateChecksum.
func (mr *MockIVideoRepositoryMockRecorder) UpdateChecksum(video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChecksum", reflect.TypeOf((*MockIVideoRepository)(nil).UpdateChecksum), video)
}

// UpdateExists mocks base method.
func (m *MockIVideoRepository) UpdateExists(video *model.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExists", video)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExists indicates an expected call of UpdateExists.
func (mr *MockIVideoRepositoryMockRecorder) UpdateExists(video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExists", reflect.TypeOf((*MockIVideoRepository)(nil).UpdateExists), video)
}
