### Start job runner manually
GET {{host}}:{{port}}/api/jobs/start-runner

### Create scan path job
POST {{host}}:{{port}}/api/jobs
Content-Type: application/json

{
  "type": "scan_path",
  "data": {"libraryPathId":"af0bc630-7e63-4664-a111-222be256f7b7"}
}

### Create generate thumbnail job
POST {{host}}:{{port}}/api/jobs
Content-Type: application/json

{
  "type": "generate_thumbnail",
  "data": {
    "videoId": "9e829a17-dd55-4dd3-85fb-0f255231b03f",
    "priority": "0",
    "height": 480,
    "width": 720,
    "timestamp": 200,
    "path": "./.temp/test2.png"
  }
}

### Create refresh metadata job
POST {{host}}:{{port}}/api/jobs
Content-Type: application/json

{
  "type":"refresh_metadata",
  "data": {
    "mediaId": "d973659b-21a0-4e4f-9eb0-29975291e608"
  }
}

### Create refresh library metadata job
POST {{host}}:{{port}}/api/jobs
Content-Type: application/json

{
  "type": "refresh_library_metadata",
  "data": {
    "libraryId": "1c72663a-ff6a-44e1-b0af-ffe55066a68b",
    "batchSize": 50
  }
}

### Create generate chapters job
POST {{host}}:{{port}}/api/jobs
Content-Type: application/json

{
  "type": "generate_chapters",
  "data": {
    "mediaId": "2b65b266-3a76-471e-838a-e5edfc51255e",
    "interval": 60,
    "maxDimension": 400,
    "overwrite": true
  }
}

### Get Jobs
GET {{host}}:{{port}}/api/jobs?parent=c42a3089-1026-42c6-ace6-64c6636afbf5&statuses[]=not_started
