### Create Library
POST {{host}}:{{port}}/api/libraries
Content-Type: application/json

{
  "name": "new library name"
}

### Get libraries
GET {{host}}:{{port}}/api/libraries

### Scan library
GET {{host}}:{{port}}/api/libraries/4267107e-15b1-4e0f-8bd7-6ba62c67a77c/scan
