### Create Library
POST {{host}}:{{port}}/api/libraryPaths
Content-Type: application/json

{
  "path": "./",
  "libraryId": "4267107e-15b1-4e0f-8bd7-6ba62c67a77c"
}

### Get all library paths
GET {{host}}:{{port}}/api/libraryPaths
