### Create Library
POST {{host}}:{{port}}/api/libraryPaths
Content-Type: application/json

{
  "path": "./",
  "libraryId": "7755d759-d0f6-4928-b8e7-5a1f13d39d88"
}

### Get all library paths
GET {{host}}:{{port}}/api/libraryPaths
