### Create Library
POST {{host}}:{{port}}/api/libraries
Content-Type: application/json

{
  "name": "new library name"
}

### Get libraries
GET {{host}}:{{port}}/api/libraries

### Scan library
GET {{host}}:{{port}}/api/libraries/7755d759-d0f6-4928-b8e7-5a1f13d39d88/scan
