### Create Library
POST {{host}}:{{port}}/api/libraryPaths
Content-Type: application/json

{
  "path": "./",
  "libraryId": "e5060115-d8d2-4330-8092-549f1a617756"
}

### Get all library paths
GET {{host}}:{{port}}/api/libraryPaths
