### Create User
POST {{host}}:{{port}}/api/users
Content-Type: application/json

{
  "username": "otherUser",
  "password": "admin"
}

### Update password
PUT {{host}}:{{port}}/api/users
Content-Type: application/json

{
  "oldPassword": "admin",
  "newPassword": "admin1",
  "repeatPassword": "admin1"
}
