//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var GenerateThumbnailsJobs = newGenerateThumbnailsJobsTable("", "GenerateThumbnailsJobs", "")

type generateThumbnailsJobsTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	Overwrite sqlite.ColumnInteger
	LibraryId sqlite.ColumnInteger
	JobId     sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type GenerateThumbnailsJobsTable struct {
	generateThumbnailsJobsTable

	EXCLUDED generateThumbnailsJobsTable
}

// AS creates new GenerateThumbnailsJobsTable with assigned alias
func (a GenerateThumbnailsJobsTable) AS(alias string) *GenerateThumbnailsJobsTable {
	return newGenerateThumbnailsJobsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GenerateThumbnailsJobsTable with assigned schema name
func (a GenerateThumbnailsJobsTable) FromSchema(schemaName string) *GenerateThumbnailsJobsTable {
	return newGenerateThumbnailsJobsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GenerateThumbnailsJobsTable with assigned table prefix
func (a GenerateThumbnailsJobsTable) WithPrefix(prefix string) *GenerateThumbnailsJobsTable {
	return newGenerateThumbnailsJobsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GenerateThumbnailsJobsTable with assigned table suffix
func (a GenerateThumbnailsJobsTable) WithSuffix(suffix string) *GenerateThumbnailsJobsTable {
	return newGenerateThumbnailsJobsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGenerateThumbnailsJobsTable(schemaName, tableName, alias string) *GenerateThumbnailsJobsTable {
	return &GenerateThumbnailsJobsTable{
		generateThumbnailsJobsTable: newGenerateThumbnailsJobsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                    newGenerateThumbnailsJobsTableImpl("", "excluded", ""),
	}
}

func newGenerateThumbnailsJobsTableImpl(schemaName, tableName, alias string) generateThumbnailsJobsTable {
	var (
		IDColumn        = sqlite.IntegerColumn("Id")
		OverwriteColumn = sqlite.IntegerColumn("Overwrite")
		LibraryIdColumn = sqlite.IntegerColumn("LibraryId")
		JobIdColumn     = sqlite.IntegerColumn("JobId")
		allColumns      = sqlite.ColumnList{IDColumn, OverwriteColumn, LibraryIdColumn, JobIdColumn}
		mutableColumns  = sqlite.ColumnList{OverwriteColumn, LibraryIdColumn, JobIdColumn}
	)

	return generateThumbnailsJobsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Overwrite: OverwriteColumn,
		LibraryId: LibraryIdColumn,
		JobId:     JobIdColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
