//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var SyncJobs = newSyncJobsTable("", "SyncJobs", "")

type syncJobsTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	LibraryId sqlite.ColumnInteger
	JobId     sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type SyncJobsTable struct {
	syncJobsTable

	EXCLUDED syncJobsTable
}

// AS creates new SyncJobsTable with assigned alias
func (a SyncJobsTable) AS(alias string) *SyncJobsTable {
	return newSyncJobsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SyncJobsTable with assigned schema name
func (a SyncJobsTable) FromSchema(schemaName string) *SyncJobsTable {
	return newSyncJobsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SyncJobsTable with assigned table prefix
func (a SyncJobsTable) WithPrefix(prefix string) *SyncJobsTable {
	return newSyncJobsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SyncJobsTable with assigned table suffix
func (a SyncJobsTable) WithSuffix(suffix string) *SyncJobsTable {
	return newSyncJobsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSyncJobsTable(schemaName, tableName, alias string) *SyncJobsTable {
	return &SyncJobsTable{
		syncJobsTable: newSyncJobsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newSyncJobsTableImpl("", "excluded", ""),
	}
}

func newSyncJobsTableImpl(schemaName, tableName, alias string) syncJobsTable {
	var (
		IDColumn        = sqlite.IntegerColumn("Id")
		LibraryIdColumn = sqlite.IntegerColumn("LibraryId")
		JobIdColumn     = sqlite.IntegerColumn("JobId")
		allColumns      = sqlite.ColumnList{IDColumn, LibraryIdColumn, JobIdColumn}
		mutableColumns  = sqlite.ColumnList{LibraryIdColumn, JobIdColumn}
	)

	return syncJobsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		LibraryId: LibraryIdColumn,
		JobId:     JobIdColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
