//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Actors = Actors.FromSchema(schema)
	Chapters = Chapters.FromSchema(schema)
	ConvertJobs = ConvertJobs.FromSchema(schema)
	FavouriteActors = FavouriteActors.FromSchema(schema)
	FavouriteVideos = FavouriteVideos.FromSchema(schema)
	GenerateChaptersJobs = GenerateChaptersJobs.FromSchema(schema)
	GenerateThumbnailsJobs = GenerateThumbnailsJobs.FromSchema(schema)
	Genres = Genres.FromSchema(schema)
	Images = Images.FromSchema(schema)
	Jobs = Jobs.FromSchema(schema)
	Libraries = Libraries.FromSchema(schema)
	LibraryPaths = LibraryPaths.FromSchema(schema)
	PlaylistVideos = PlaylistVideos.FromSchema(schema)
	Playlists = Playlists.FromSchema(schema)
	Progress = Progress.FromSchema(schema)
	RelatedVideos = RelatedVideos.FromSchema(schema)
	SyncJobs = SyncJobs.FromSchema(schema)
	Users = Users.FromSchema(schema)
	VideoActors = VideoActors.FromSchema(schema)
	VideoGenres = VideoGenres.FromSchema(schema)
	VideoImages = VideoImages.FromSchema(schema)
	Videos = Videos.FromSchema(schema)
}
