// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/image/image.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/image/image.go
//

// Package mock_imageRepository is a generated GoMock package.
package mock_imageRepository

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/slugger7/exorcist/internal/db/exorcist/public/model"
	imageRepository "github.com/slugger7/exorcist/internal/repository/image"
	gomock "go.uber.org/mock/gomock"
)

// MockImageRepository is a mock of ImageRepository interface.
type MockImageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockImageRepositoryMockRecorder
	isgomock struct{}
}

// MockImageRepositoryMockRecorder is the mock recorder for MockImageRepository.
type MockImageRepositoryMockRecorder struct {
	mock *MockImageRepository
}

// NewMockImageRepository creates a new mock instance.
func NewMockImageRepository(ctrl *gomock.Controller) *MockImageRepository {
	mock := &MockImageRepository{ctrl: ctrl}
	mock.recorder = &MockImageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageRepository) EXPECT() *MockImageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockImageRepository) Create(m *model.Image) (*model.Image, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", m)
	ret0, _ := ret[0].(*model.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockImageRepositoryMockRecorder) Create(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockImageRepository)(nil).Create), m)
}

// GetById mocks base method.
func (m *MockImageRepository) GetById(arg0 uuid.UUID) (*imageRepository.MediaImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0)
	ret0, _ := ret[0].(*imageRepository.MediaImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockImageRepositoryMockRecorder) GetById(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockImageRepository)(nil).GetById), arg0)
}

// GetByMediaId mocks base method.
func (m *MockImageRepository) GetByMediaId(arg0 uuid.UUID) (*imageRepository.MediaImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMediaId", arg0)
	ret0, _ := ret[0].(*imageRepository.MediaImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMediaId indicates an expected call of GetByMediaId.
func (mr *MockImageRepositoryMockRecorder) GetByMediaId(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMediaId", reflect.TypeOf((*MockImageRepository)(nil).GetByMediaId), arg0)
}
