// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/library_path/library_path.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/library_path/library_path.go
//

// Package mock_libraryPathRepository is a generated GoMock package.
package mock_libraryPathRepository

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/slugger7/exorcist/internal/db/exorcist/public/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLibraryPathRepository is a mock of LibraryPathRepository interface.
type MockLibraryPathRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLibraryPathRepositoryMockRecorder
	isgomock struct{}
}

// MockLibraryPathRepositoryMockRecorder is the mock recorder for MockLibraryPathRepository.
type MockLibraryPathRepositoryMockRecorder struct {
	mock *MockLibraryPathRepository
}

// NewMockLibraryPathRepository creates a new mock instance.
func NewMockLibraryPathRepository(ctrl *gomock.Controller) *MockLibraryPathRepository {
	mock := &MockLibraryPathRepository{ctrl: ctrl}
	mock.recorder = &MockLibraryPathRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLibraryPathRepository) EXPECT() *MockLibraryPathRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLibraryPathRepository) Create(path string, libraryId uuid.UUID) (*model.LibraryPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", path, libraryId)
	ret0, _ := ret[0].(*model.LibraryPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLibraryPathRepositoryMockRecorder) Create(path, libraryId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLibraryPathRepository)(nil).Create), path, libraryId)
}

// GetAll mocks base method.
func (m *MockLibraryPathRepository) GetAll() ([]model.LibraryPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.LibraryPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockLibraryPathRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLibraryPathRepository)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockLibraryPathRepository) GetById(id uuid.UUID) (*model.LibraryPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*model.LibraryPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockLibraryPathRepositoryMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockLibraryPathRepository)(nil).GetById), id)
}

// GetByLibraryId mocks base method.
func (m *MockLibraryPathRepository) GetByLibraryId(libraryId uuid.UUID) ([]model.LibraryPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLibraryId", libraryId)
	ret0, _ := ret[0].([]model.LibraryPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLibraryId indicates an expected call of GetByLibraryId.
func (mr *MockLibraryPathRepositoryMockRecorder) GetByLibraryId(libraryId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLibraryId", reflect.TypeOf((*MockLibraryPathRepository)(nil).GetByLibraryId), libraryId)
}

// GetContainingPath mocks base method.
func (m *MockLibraryPathRepository) GetContainingPath(path string) ([]model.LibraryPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainingPath", path)
	ret0, _ := ret[0].([]model.LibraryPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainingPath indicates an expected call of GetContainingPath.
func (mr *MockLibraryPathRepositoryMockRecorder) GetContainingPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainingPath", reflect.TypeOf((*MockLibraryPathRepository)(nil).GetContainingPath), path)
}
