// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/person/person.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/person/person.go
//

// Package mock_personRepository is a generated GoMock package.
package mock_personRepository

import (
	reflect "reflect"

	model "github.com/slugger7/exorcist/internal/db/exorcist/public/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIPersonRepository is a mock of IPersonRepository interface.
type MockIPersonRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPersonRepositoryMockRecorder
	isgomock struct{}
}

// MockIPersonRepositoryMockRecorder is the mock recorder for MockIPersonRepository.
type MockIPersonRepositoryMockRecorder struct {
	mock *MockIPersonRepository
}

// NewMockIPersonRepository creates a new mock instance.
func NewMockIPersonRepository(ctrl *gomock.Controller) *MockIPersonRepository {
	mock := &MockIPersonRepository{ctrl: ctrl}
	mock.recorder = &MockIPersonRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPersonRepository) EXPECT() *MockIPersonRepositoryMockRecorder {
	return m.recorder
}

// AddToMedia mocks base method.
func (m *MockIPersonRepository) AddToMedia(mediaPeople []model.MediaPerson) ([]model.MediaPerson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToMedia", mediaPeople)
	ret0, _ := ret[0].([]model.MediaPerson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToMedia indicates an expected call of AddToMedia.
func (mr *MockIPersonRepositoryMockRecorder) AddToMedia(mediaPeople any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToMedia", reflect.TypeOf((*MockIPersonRepository)(nil).AddToMedia), mediaPeople)
}

// Create mocks base method.
func (m *MockIPersonRepository) Create(names []string) ([]model.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", names)
	ret0, _ := ret[0].([]model.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIPersonRepositoryMockRecorder) Create(names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPersonRepository)(nil).Create), names)
}

// GetByName mocks base method.
func (m *MockIPersonRepository) GetByName(name string) (*model.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", name)
	ret0, _ := ret[0].(*model.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockIPersonRepositoryMockRecorder) GetByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockIPersonRepository)(nil).GetByName), name)
}

// RemoveFromMedia mocks base method.
func (m *MockIPersonRepository) RemoveFromMedia(mediaPerson model.MediaPerson) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromMedia", mediaPerson)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromMedia indicates an expected call of RemoveFromMedia.
func (mr *MockIPersonRepositoryMockRecorder) RemoveFromMedia(mediaPerson any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromMedia", reflect.TypeOf((*MockIPersonRepository)(nil).RemoveFromMedia), mediaPerson)
}
