### Get All videos
GET {{host}}:{{port}}/api/media?limit=50

### Get media by id
GET {{host}}:{{port}}/api/media/0fa21151-458f-4a33-aa89-3e374952ddd8

### Get video media by id
GET {{host}}:{{port}}/api/media/video/064eb817-2347-4648-9608-84a86f7b303d

### Add People to media
PUT {{host}}:{{port}}/api/media/eff222d5-54bf-47ab-88d5-b54baf085284/people
Content-Type: application/json

[
  "not kevin",
  "kevin"
]

### Add Tags to media
PUT {{host}}:{{port}}/api/media/b879594f-431b-43e4-8e2c-c4e91796426e/tags
Content-Type: application/json

[
  "tag 1",
  "tag 2",
  "tag 3"
]

### Add Tag to media
PUT {{host}}:{{port}}/api/media/b879594f-431b-43e4-8e2c-c4e91796426e/tags/d242b4a1-90d0-4db5-a59e-f62984401600

### Remove tag from media
DELETE {{host}}:{{port}}/api/media/b879594f-431b-43e4-8e2c-c4e91796426e/tags/d242b4a1-90d0-4db5-a59e-f62984401600

### Add Person to Media
PUT {{host}}:{{port}}/api/media/b879594f-431b-43e4-8e2c-c4e91796426e/people/47f31a90-18e4-4d27-b6fb-ac63d58ad514

### Remove Person to Media
DELETE {{host}}:{{port}}/api/media/b879594f-431b-43e4-8e2c-c4e91796426e/people/47f31a90-18e4-4d27-b6fb-ac63d58ad514

### Get Media by tags
GET {{host}}:{{port}}/api/media?tags=why not another

### Delete Media
DELETE {{host}}:{{port}}/api/media/0fa21151-458f-4a33-aa89-3e374952ddd8?physical=true

### Upsert Progress
PUT {{host}}:{{port}}/api/videos/2b65b266-3a76-471e-838a-e5edfc51255e?progress=6
