# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: go build -v ./cmd/exorcist

    - name: Setup FFmpeg
      uses: federicocarboni/setup-ffmpeg@v3.1
      
    - name: Test
      run: go test -v ./...

    - name: Install tygo
      run: go install github.com/gzuidhof/tygo@v0.2.18

    - name: Generate FE Types
      run: make dtos
